<?php

function ckeditor_codesnippet_wysiwyg_plugin($editor, $version) {

  switch ($editor) {
    case 'ckeditor':
      return array(
        'codesnippet' => array(
          'path' => drupal_get_path('module', 'ckeditor_codesnippet') . '/plugin/codesnippet',
          'buttons' => array(
            'CodeSnippet' => t('Code Snippet'),
          ),
          'load' => TRUE,
        ),
      );
      break;
  }
}

function ckeditor_codesnippet_wysiwyg_editor_settings_alter(&$settings, $context) {

  //if the editor name is ckeditor
  //We'll set configurations for ckedito
  if ($context['profile']->editor == 'ckeditor') {



    //this property is used by ckeditor to load a custom javascript configuration file.
    $settings['customConfig'] = '/sites/all/modules/custom/ckeditor_codesnippet/js/config.js';
  }


}